### ISSUE TITLE
Cannot generate parsed pseudoClassSelector

### ISSUE THREAD

**Issue by andersnm** [gajus/scalpel#10]
Hi,

Using scalpel 2.1.0

```js
    selectorParser = createParser();
    selectorGenerator = createGenerator();
    tokens = selectorParser.parse(".rtl .u-phone:after");
    selectorGenerator.generate(tokens)
```

Gives error:
```
TypeError: Cannot read property 'length' of undefined
at length (node_modules/scalpel/src/createGenerator.js:34:28)
at Object.renderSelector [as generate] (node_modules/scalpel/src/createGenerator.js:58:24)
```

Workaround:
```ts
    private fixScalpelBug(tokens: any[]) {
        for (let tokenItem of tokens) {
            if (tokenItem.type === 'pseudoClassSelector') {
                tokenItem.parameters = tokenItem.parameters || [];
            }

            if (tokenItem.body) {
                this.fixScalpelBug(tokenItem.body);
            }
        }
    }
```

**Comment by gajus** [comment]
```js
import {
  createParser,
  createGenerator
} from './src';

const selectorParser = createParser();
const selectorGenerator = createGenerator();
const tokens = selectorParser.parse(".rtl .u-phone:after");
console.log(selectorGenerator.generate(tokens));

```

```
.rtl .u-phone:after

```

Cannot replicate.

**Comment by gajus** [comment]
I have just released a new version with bumped dependencies. It is unlikely, but maybe that fixed the issue described here.

**Comment by andersnm** [comment]
Indeed, it was fixed in https://github.com/gajus/scalpel/commit/631b161dc416e590360be439483927e420cecbc8

Latest release should fix it. Thanks!
